// Clasificación de productos en subcategorías por reglas de palabras clave,
// alineada con la estructura de departamentos de Arsenal Sports.
// El CSV no tiene columna de subcategoría: se deriva del nombre del producto.

interface Rule {
  sub: string;
  re: RegExp;
  // Si alguna coincide, la regla no aplica (p. ej. piezas "FOR <modelo>" no son réplicas)
  not?: RegExp;
}

const RULES: Record<string, Rule[]> = {
  Airsoft: [
    { sub: 'CARGADORES PARA RÉPLICAS', re: /MAGAZINE|DRUM|SPEED LOADER/ },
    { sub: 'BATERÍAS Y CARGADORES', re: /BATTERY|BATERIA|CHARGER|CARREGADOR|BALANCER|LI-?PO|NI-?MH|LI-?ION|11\.1V|7\.4V/ },
    { sub: 'GRANADAS DE AIRSOFT', re: /GRENADE|GRANADA|LAUNCHER|LAUCHER|THUNDER|CLAYMORE|MINES?|\bSHELLS?\b|40MM/ },
    // Equipamiento de carga HPA / PCP que viene mal etiquetado como Airsoft en el CSV
    { sub: 'BBS / GREEN GAS / CO2 / HPA', re: /\bPCP\b|HAND PUMP/ },
    {
      sub: 'RÉPLICAS DE AIRSOFT',
      re: /AEG|GBBR|GBB|BLOWBACK|BOLT ACTION|ELECTRIC|SPRING|SPING|SNIPER|SMG|SHOTGUN|RIFLE|PISTOL|REVOLVER|PDW|CARBINE|MACHINE GUN/,
      not: /\b(FOR|SET|REPAIR|REPLACEMENT)\b/,
    },
    { sub: 'SPEEDSOFT', re: /SPEEDSOFT/ },
    { sub: 'PIEZAS PARA SNIPERS', re: /VSR|L96|SSG|MB0|SNIPER|\bSRS\b|\bT10\b/ },
    { sub: 'PIEZAS PARA PISTOLAS', re: /HI-CAPA|GLOCK|1911|AAP-? ?01|G SERIES|G1[789]\b|G26\b|\bM9\b|P226|USP|MK23|DESERT EAGLE|VP9|KP-?0[68]/ },
    { sub: 'BBS / GREEN GAS / CO2 / HPA', re: /\bBBS?\b|SEAMLESS|GREEN GAS|\bHPA\b|\bCO2\b|PROPANE|SILICONE OIL|GAS CARTRIDGE/ },
    {
      sub: 'PIEZAS INTERNAS',
      re: /GEAR SET|GEARS?\b|HOP-?UP|BUCKING|INNER BARREL|MOSFET|ETU\b|PISTON|SPRING GUIDE|SPRING\b|NOZZLE|TAPPET|SECTOR|MOTOR\b|ENGINE|VALVE|O-?RING|SEAL\b|SHIMS?|BEARING|BUSHING|ANTI-?REVERSAL|WIRE|SWITCH\b|CYLINDER|CONVERSION KIT|UPGRADE|FIRING|\bPIN\b|DELAYER|GEARBOX|BARREL|SELECTOR|\bLATCH\b|\bLEVER\b|TAMIYA|CONNECTOR|\bPLUGS?\b|FUSE|DISCONNECTOR|\bPLATES?\b|ASSEMBLY|BOLT (CATCH|LOCK|STOP)|CUT OFF/,
      not: /OUTER BARREL/,
    },
    {
      sub: 'PIEZAS EXTERNAS',
      re: /STOCK|GRIP|RAIL|HANDGUARD|SUPPRESSOR|SILENCER|FLASH HIDER|CHARGING HANDLE|SLING|BIPOD|BUFFER|RECEIVER|\bBODY\b|HAND STOP|FOREGRIP|MOCK|MOUNT|BASE PLATE|FLOOR|TRACER|HELMET|VEST|COVER|OUTER BARREL|THREADED|MUZZLE|\bCCW\b|\bCW\b|14MM|TRIPOD|REMOTE LINE|\bSIGHTS?\b|TRIGGER GUARD|RUBBER/,
    },
    { sub: 'PIEZAS PARA RIFLES A GAS', re: /M4\b|M16\b|AK4[79]|AKM\b|SCAR|HK416|SR25|M110|THOMPSON|MP5|MP7|AUG\b|G36\b/ },
  ],
  Airgun: [
    { sub: 'PISTOLAS Y REVÓLVERES', re: /PISTOL|REVOLVER/ },
    { sub: 'CARABINAS DE AIRE', re: /RIFLE|CARABINA/ },
    { sub: 'CARGADORES', re: /MAGAZINE|DRUM/ },
    { sub: 'PERDIGONES Y PROYECTILES', re: /PELLET|DIABOLO|CHUMBO|PROJECTILE|\bJSB\b|HADES|KAISER/ },
    { sub: 'PIEZAS Y ACCESORIOS', re: /CILINDRO|COMPRESSOR|COMPRESOR|HAND ?PUMP|BOMBA|ESTACA[Cc][ãaO]O|ESTACION|HPA|TANK|PSI|FILL PROBE|ADAPTER|REGULATOR|CHRONY|CRONO/ },
  ],
  Paintball: [
    { sub: 'MARCADORES', re: /MARCADOR|MARKER/ },
    { sub: 'MÁSCARAS Y LENTES', re: /MASK|MASCARA|GOGGLE|LENTE|LENS/ },
    { sub: 'LOADERS Y CARGADORES', re: /LOADER|MAGAZINE|DRUM|HOPPER/ },
    { sub: 'CINTURONES PARA PODS Y CILINDROS', re: /HARNESS|CINTO|BELT|\bPODS?\b/ },
    { sub: 'CO2 / HPA', re: /CO2|HPA|TANK|CILINDRO|ESTACAO|RECARGA|INFLADOR|CHARGING HOSE|REMOTE LINE/ },
    { sub: 'PROYECTILES PAINTBALL', re: /PEPPER BALL|PIMENTA|RUBBER BALL|\bBALLS\b|PAINTBALLS\b/ },
    { sub: 'CUSTOMIZACIÓN Y TUNE-UP', re: /BARREL|CANO|KIT|UPGRADE|SUPPRESSOR|SHROUD|TRIGGER|HOUSING|FEED/ },
  ],
  'Óptica e Iluminación': [
    { sub: 'ACOG', re: /ACOG/ },
    { sub: 'MIRAS RED DOT Y VERDE DOT', re: /RED DOT|RED DOR|REFLEX|HOLO|RMR|PRISM|DOT SIGHT|VERDE DOT/ },
    { sub: 'MIRAS TÉRMICAS', re: /THERMAL/ },
    { sub: 'SPOTTING SCOPES', re: /SPOTTING/ },
    { sub: 'MIRAS TELESCÓPICAS', re: /SCOPE|LPVO|LUNETE/ },
    { sub: 'MIRAS DE VISIÓN NOCTURNA', re: /NIGHT VISION|NVG|850NM|SYTONG|\bIR\b/ },
    { sub: 'BINOCULARES', re: /BINOCULAR/ },
    { sub: 'TELÉMETROS (RANGEFINDERS)', re: /RANGEFINDER|TELEMETRO/ },
    { sub: 'MIRAS DE FIBRA Y TRITIUM', re: /FIBER|FIBRE|TRITIUM|FIBRA/ },
    {
      sub: 'LUCES Y LÁSERES',
      re: /FLASHLIGHT|\bLIGHT\b|LASER|LANTERN|TORCH|HEADLAMP|OLIGHT|MODLITE|SCOUT LIGHT|TAPE SWITCH|REMOTE CONTROL|BATTERY CASE/,
    },
    { sub: 'ANILLOS DE MIRA', re: /\bRINGS?\b|LEVEL BUBBLE|FLIP-?CAP|SADDLE|BUBBLE LEVEL/ },
    { sub: 'SOPORTES Y BASES DE MIRA', re: /MOUNT|BASE\b|PICATINNY|WEAVER|DOVETAIL|RISER|CANTILEVER|ONE PIECE/ },
  ],
  'Fitness & Recuperación': [
    {
      sub: 'FISIOTERAPIA Y RECUPERACIÓN MUSCULAR',
      re: /CRIOTERAPIA|CRYO|MASAJE|MASSAGE|IASTM|VENTOSA|ELECTRODO|ELECTROTERAPIA|LUZ ROJA|RED LIGHT|INFRARROJO|SAUNA|INMERSION|BANERA|COMPRESSION THERAPY|RECUPERACION|RECOVERY|FOAM ROLLER|RODILLO|KINESIO|FASCIA|MIOFASCIAL|PEDRA|BOMBILLA|CAST\b/,
    },
    { sub: 'YOGA Y PILATES', re: /YOGA|PILATES|COLCHONETA|\bMAT\b|ZAFU|BLOQUE|LADRILLO/ },
    { sub: 'MOVILIDAD, CORE Y EQUILIBRIO', re: /BALANCE|BOSU|EQUILIBRIO|MOBILITY|MOVILIDAD|\bCORE\b|AB MAT|SIT UP|HALF BALL/ },
    { sub: 'ENTRENAMIENTO FUNCIONAL', re: /BANDAS? ELASTIC|TUBO ELASTICO|EXTENSOR|RESISTANCE|SUSPENSION|TRX|POWER BAG|SANDBAG|SLAM|MEDICINE BALL|WALL BALL|PELOTA (DE PARED|PESO)|GYM HAMMER/ },
    { sub: 'ACONDICIONAMIENTO FÍSICO', re: /CUERDA|JUMP ROPE|PARACAIDAS|SPEED CHUTE|TRAINING ROPE|BATTLING|AGILIDAD|ESCALERA|CONOS|VELOCIDAD|SLED|TRINEO|CARDIO|LAMPARA/ },
  ],
  'Outdoor & Survival': [
    { sub: 'MOTORES NÁUTICOS', re: /MOTOR|HASWING|HELICE|PROPELLER/ },
    { sub: 'KAYAKS', re: /KAYAK|CAIQUE/ },
    { sub: 'BARCOS Y CANOAS', re: /BOAT|BARCO|CANOA|CANOE|RAFT|BOTE\b/ },
    { sub: 'SOPORTES PARA BARCOS Y KAYAKS', re: /VINMOUNTS|MOUNT|CLAMP|BRACKET|TRANSDUCER|SOCKET ARM|GLUE-ON/ },
    { sub: 'STAND UP PADDLE (SUP)', re: /STAND UP PADDLE|\bSUP\b|PADDLE BOARD/ },
    { sub: 'MOCHILAS TÉRMICAS', re: /MOCHILA TERMICA|\bCOOLER\b|DUFFLE/ },
    { sub: 'BOLSAS TÉRMICAS', re: /BOLSA TERMICA|ICE PACK|INSULATED/ },
    { sub: 'BOTELLAS TÉRMICAS', re: /GARRAFA|BOTELLA/ },
    { sub: 'RED DE CAMUFLAJE MILITAR', re: /CAMOUFLAGE|CAMUFLAGEM/ },
    { sub: 'SILLAS Y MESAS DE CAMPING', re: /CHAIR|SILLA|MESA|\bTABLE\b|DESK/ },
    { sub: 'LINTERNAS DE ACAMPAMENTO', re: /LANTERNA|LANTERN|LINTERNA|FLASHLIGHT|HEADLAMP|\bLED\b|GLOW/ },
    { sub: 'PRIMEROS AUXILIOS', re: /FIRST AID|TOURNIQUET|MEDICAL|TRAUMA|SOCORRO|PARAMEDIC|EMERGENCY KIT|SCISSOR|SHEAR/ },
    { sub: 'CUCHILLOS', re: /FACAS|KNIFE|MACHADO|\bAXE\b|BATTLEAXE|CANIVETE|MACHETE|MACHTAC/ },
    { sub: 'EQUIPOS DE SALVAMENTO', re: /LIFE JACKET|SALVAVIDAS|SALVAMENTO|RESCUE|INFLATOR/ },
    { sub: 'GAZEBOS PORTÁTILES', re: /GAZEBO/ },
    { sub: 'PULSERAS DE SUPERVIVENCIA', re: /PARACORD|BRACELET|PULSEIRA/ },
    { sub: 'GPS Y RASTREADORES PARA ANIMALES', re: /GPS|RASTREADOR|TRACKER|FISH FINDER|SONDA/ },
  ],
  'Deportes y Ocio': [
    { sub: 'BEACH TENNIS', re: /BEACH/ },
    { sub: 'PICKLEBALL', re: /PICKLE/ },
    { sub: 'PÁDEL', re: /PADEL/ },
    { sub: 'ACCESORIOS', re: /OVER GRIP|GRIP|CORDA|STRING|BANDA/ },
    { sub: 'PELOTAS', re: /BALL/ },
    { sub: 'SUP (STAND UP PADDLE)', re: /\bSUP\b|PADDLE/ },
  ],
  'Marcadores No Letales': [
    { sub: 'MARCADORES', re: /REVOLVER|PISTOL|MARCADOR|CP300|T4E|TR50|TP50/ },
    { sub: 'CARGADORES', re: /MAGAZINE/ },
    { sub: 'ACCESORIOS', re: /RUBBER BALL|\bBALLS\b/ },
  ],
  'Productos Coca-Cola': [
    { sub: 'AURICULARES Y PARLANTES', re: /FONE|SPEAKER|CAIXA DE SOM|EARBUDS|PHONE HOLDER|AURICULAR|PARLANTE/ },
  ],
  'Ofertas y Promociones': [{ sub: 'COMBOS PROMOCIONALES', re: /./ }],
};

// Subcategoría por defecto cuando el producto no calza en ninguna regla
const FALLBACK: Record<string, string> = {
  Airgun: 'PIEZAS Y ACCESORIOS',
  Paintball: 'PIEZAS DE REPOSICIÓN',
  'Óptica e Iluminación': 'ACCESORIOS DE MIRA',
  'Fitness & Recuperación': 'EQUIPOS DE ENTRENAMIENTO / TECNOLOGÍA',
  'Deportes y Ocio': 'ACCESORIOS',
  'Marcadores No Letales': 'ACCESORIOS',
  'Productos Coca-Cola': 'VASOS Y BOTELLAS TÉRMICAS',
  'Ofertas y Promociones': 'COMBOS PROMOCIONALES',
};

export function classifySubcategory(categoria: string, nombreProducto: string): string | null {
  const rules = RULES[categoria];
  if (!rules) return null;
  const text = nombreProducto
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toUpperCase();
  for (const rule of rules) {
    if (rule.re.test(text) && !(rule.not && rule.not.test(text))) return rule.sub;
  }
  return FALLBACK[categoria] ?? null;
}
